/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "provenance-protos.h"

std::string provenance_protos::Greeter::greeting() {
    return std::string("Hello, World!");
}
