/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef PROVENANCE_PROTOS_H
#define PROVENANCE_PROTOS_H

#ifdef _WIN32
#define PROVENANCE_PROTOS_EXPORT_FUNC __declspec(dllexport)
#else
#define PROVENANCE_PROTOS_EXPORT_FUNC
#endif

#include <string>

namespace provenance_protos {
    class Greeter {
        public:
        std::string PROVENANCE_PROTOS_EXPORT_FUNC greeting();
    };
}

#endif
